import './globals.css'
import { Inter, Comfortaa, Alex_Brush } from 'next/font/google'

const inter = Comfortaa({ subsets: ['latin'], weight:'400', variable:'--comfortaa' })
const alex = Alex_Brush({subsets:['latin'], weight:'400', variable:'--alex' })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${alex.variable}`}>{children}</body>
    </html>
  )
}
