export {default as Nav} from './Nav'
export {default as Cover} from './Cover'
export {default as Companies} from './Companies'
export {default as About} from './About'
export {default as Cards} from './Card'
export {default as Workflow} from './Workflow'
export {default as Qualities} from './Qualities'
export {default as Services} from './Services'